
// The list of socket message id
//

enum SocketMessageId
{
	SMI_TOSERVER_SEARCH_SERVER = 1,
	SMI_TOCLIENT_GAME_NAME,
	SMI_TOSERVER_ASK_CONNEXION,
	SMI_TOCLIENT_GET_PLAYER_NAME,
	SMI_TOSERVER_SET_PLAYER_NAME,
	SMI_TOCLIENT_PLAYERS_LIST,
	SMI_TOSERVER_MESSAGE_TO_EVERYONE,
	SMI_TOCLIENT_MESSAGE_TO_EVERYONE,
	SMI_TOCLIENT_BATTLEFIELD_NAME,
	SMI_TOCLIENT_PLAYER_MAX,
	SMI_TOCLIENT_GAME_POINT,
	SMI_TOCLIENT_GAME_TYPE,
	SMI_TOCLIENT_VIRTUALSCAPE_VERSION,
	SMI_TOCLIENT_TILES,
	SMI_TOCLIENT_ACTION,
	SMI_TOSERVER_ARMYCHOOSED,
	SMI_TOCLIENT_ARMYCHOOSED,
	SMI_TOSERVER_FIGUREPLACED,
	SMI_TOCLIENT_FIGUREPLACED,
	SMI_TOSERVER_FIGUREREMOVED,
	SMI_TOCLIENT_FIGUREREMOVED,
	SMI_TOSERVER_FIGUREMOVED,
	SMI_TOCLIENT_FIGUREMOVED,
	SMI_TOSERVER_ATTACK,
	SMI_TOCLIENT_ATTACK,
	SMI_TOSERVER_DEFENSE,
	SMI_TOCLIENT_DEFENSE,
	SMI_TOSERVER_NEXT_TURN,
	SMI_TOCLIENT_NEXT_TURN,
	SMI_TOSERVER_INCREMENT_LIFE,
	SMI_TOCLIENT_INCREMENT_LIFE,
	SMI_TOSERVER_DECREMENT_LIFE,
	SMI_TOCLIENT_DECREMENT_LIFE,
	SMI_TOSERVER_ADD_PREDICTED_MARQUER,
	SMI_TOCLIENT_ADD_PREDICTED_MARQUER,
	SMI_TOSERVER_SHOW_PREDICTED_MARQUER,
	SMI_TOCLIENT_SHOW_PREDICTED_MARQUER,
	SMI_TOSERVER_DIE_20_FACES,
	SMI_TOCLIENT_DIE_20_FACES,

	SMI_TODEDICATEDSERVER_NEW_SERVER=1001,
	SMI_TODEDICATEDSERVER_GET_SERVER_LIST,
	SMI_FROMDEDICATEDSERVER_SET_SERVER_LIST,
	SMI_TODEDICATEDSERVER_GAME_BEGIN,
	SMI_TODEDICATEDSERVER_GAME_END
};






