#ifndef _GAMEACTIONVIEW_H_
#define _GAMEACTIONVIEW_H_

#include "Resource.h"
#include <afxcmn.h>
#include <afxwin.h>

#ifndef __AFXEXT_H__
#include <afxext.h>
#endif

class CGameActionView : public CFormView
{
	bool m_IsInit;

//************
// The methods
//************
public:
	// The constructor
	CGameActionView();
	// The destructor
	~CGameActionView();
	// Create the window
	void	Create(CWnd* Parent);
	// Add a message receive from other players
	void	AddAction( bool IsMine, CString PlayerName, int ActionType );
	// Add a string
	void	AddString( bool IsMine, CString PlayerName, CString Text );
	// Close the last action in the display list
	void	CloseLastAction();
	// Reset all the actions
	void	ResetAction();

//******************
// Generated by VC++
//******************

protected:
	DECLARE_DYNCREATE(CGameActionView)

// Form Data
public:
	//{{AFX_DATA(CGameActionView)
	enum { IDD = IDD_GAMEACTIONVIEW };
	//}}AFX_DATA

// Attributes
public:

// Operations
public:

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CGameActionView)
	public:
	virtual void OnInitialUpdate();
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	virtual void PostNcDestroy();
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(CGameActionView)
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
public:
	afx_msg int OnCreate(LPCREATESTRUCT lpCreateStruct);
public:
	afx_msg void OnSize(UINT nType, int cx, int cy);
public:
	afx_msg void OnMove(int x, int y);
public:
	afx_msg void OnBnClickedButtonSend();
};

#endif // #ifndef _GAMEACTIONVIEW_H_
