//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HeroscapeEditor.rc
//
#define IDS_FAILED_INIT_OPENGLEXT       1
#define IDS_OPENGLEXT_REQUIREMENT       2
#define IDS_VIEW3DTOOLBARTITLE          3
#define IDS_ACTIONDONE                  4
#define IDS_ULANIVA_GLYPH               5
#define IDS_THORIAN_GLYPH               6
#define IDS_CREVCOR_GLYPH               7
#define IDS_NILREND_GLYPH               8
#define IDS_ORELD_GLYPH                 9
#define IDS_PROFTAKA_GLYPH              10
#define IDS_WANNOK_GLYPH                11
#define IDS_HIVE                        12
#define IDS_REMAINING1                  13
#define IDS_REMAINING2                  14
#define IDS_REMAINING3                  15
#define IDS_TICALLA_PALM                16
#define IDS_TICALLA_GRASS               17
#define IDS_RED_BLUE                    18
#define IDS_RED_GREEN                   19
#define IDS_RED_CYAN                    20
#define IDS_DUNGEON_HEX                 21
#define IDS_SHADOW                      22
#define IDS_DUNGEON                     23
#define IDS_OUTCROP                     24
#define IDS_ARROW_GRUTS1_3              25
#define IDS_ARROW_GRUTS2_3              26
#define IDS_ARROW_GRUTS3_3              27
#define IDS_KELDA_THE_KYRIE_WARRIOR     28
#define IDS_BLADE_GRUTS1_4              29
#define IDS_BLADE_GRUTS2_4              30
#define IDS_BLADE_GRUTS3_4              31
#define IDS_BLADE_GRUTS4_4              32
#define IDS_MARCUS_DECIMUS_GALLUS       33
#define IDS_OMNICRON_SNIPERS1_3         34
#define IDS_ROMAN_ARCHERS               35
#define IDS_ROMAN_LEGIONNAIRS1_4        36
#define IDS_ROMAN_LEGIONNAIRS2_4        37
#define IDS_ROMAN_LEGIONNAIRS3_4        38
#define IDS_ROMAN_LEGIONNAIRS4_4        39
#define IDS_TAELORD_THE_KYRIE_WARRIOR   40
#define IDS_TORNAK                      41
#define IDS_VENOC_VIPERS                42
#define IDS_VENOC_WARLORD               43
#define IDS_GAMETOOLBARTITLE            44
#define IDS_FREEGAME                    45
#define IDS_ALL_FIGURE_PLACED           46
#define IDS_PLACED_ARMY                 47
#define IDS_REMOVED_ARMY                48
#define IDS_MOVED_ARMY                  49
#define IDS_ATTACK_LAUNCH               50
#define IDS_DEFENSE_LAUNCH              51
#define IDS_ATTACK_DICE                 52
#define IDS_DICE_FORCED                 53
#define IDS_DICE_NOT_FORCED             54
#define IDS_NEXT_TURN                   55
#define IDS_CONTEXTUALMENU_ADDONELIFE   56
#define IDS_CONTEXTUALMENU_REMOVEONELIFE 57
#define IDS_INCREMENT_ARMY_LIFE         58
#define IDS_DECREMENT_ARMY_LIFE         59
#define IDS_CONTEXTUALMENU_ADDPREDICTEDX 60
#define IDS_ADD_PREDICTED_MARQUER       61
#define IDS_CONTEXTUALMENU_ADDPREDICTED1 62
#define IDS_CONTEXTUALMENU_ADDPREDICTED2 63
#define IDS_CONTEXTUALMENU_ADDPREDICTED3 64
#define IDS_CONTEXTUALMENU_SHOWPREDICTED 65
#define IDS_SHOW_PREDICTED_MARQUER      66
#define IDS_DIE_20_FACES                67
#define IDS_SERVER_LIST_COLUMNS         68
#define IDS_BASICRULES                  69
#define IDS_EXPERTRULES                 70
#define IDS_CONTEXTUALMENU_REMOVEMARKER 71
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_FILE_VERSION_TOO_RECENT     101
#define IDS_AUTHOR2P                    102
#define IDS_LEVELNUMBER                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_GRASS                       105
#define IDS_ROCK                        106
#define IDS_SAND                        107
#define IDS_LIQUIDE                     108
#define IDS_LAVA                        109
#define IDS_ROAD                        110
#define IDS_SNOW                        111
#define IDS_TREE                        112
#define IDS_RUIN                        113
#define IDS_WALL                        114
#define IDS_GLACIER                     115
#define IDS_GLYPH                       116
#define IDS_START                       117
#define IDS_UNKNOWN_GLYPH               118
#define IDS_ASTRID_GLYPH                119
#define IDS_GERDA_GLYPH                 120
#define IDS_IVOR_GLYPH                  121
#define IDS_VALDA_GLYPH                 122
#define IDS_DRAGMAR_GLYPH               123
#define IDS_BRANDAR_GLYPH               124
#define IDS_KELDA_GLYPH                 125
#define IDS_ERLAND_GLYPH                126
#define IDS_MITONSOUL_GLYPH             127
#define IDR_MAINFRAME                   128
#define IDR_HeroscapeEditorTYPE         129
#define IDR_VIRTUALSCAPE2D              129
#define IDB_HEXBACKGROUND               130
#define IDS_OBJECT                      130
#define IDS_OBJECTWINDOW                131
#define IDD_GAMECHATVIEW                131
#define IDS_RED                         132
#define IDB_OBJECTVIEW                  133
#define IDS_GREEN                       133
#define IDR_TOOLBARVIEW                 134
#define IDS_BLUE                        134
#define IDS_YELLOW                      135
#define IDB_VIEWTOOLBAR                 136
#define IDS_VIOLET                      136
#define IDR_TOOLBAROBJECT               137
#define IDS_CYAN                        137
#define IDB_OBJECTTOOLBAR               138
#define IDS_ORANGE                      138
#define IDB_GENERALTOOLBAR              139
#define IDS_PURPLE                      139
#define IDB_BACKGROUND                  140
#define IDS_NOT_DEFINE                  140
#define IDD_CONFIG_MATERIAL             141
#define IDS_FILEVERSION_TOO_RECENT      141
#define IDB_3DVIEWTOOLBAR               141
#define IDD_CONFIG_DOC                  142
#define IDS_ICE                         142
#define IDS_LAVAFIELD                   143
#define IDS_WATER                       144
#define IDS_GENERALTOOLBARTITLE         145
#define IDS_VIEW2DTOOLBARTITLE          146
#define IDB_BITMAP1                     146
#define IDB_BRUSH_ONION                 146
#define IDS_OBJECTTOOLBARTITLE          147
#define IDD_PREFERENCE                  147
#define IDS_LODIN_GLYPH                 148
#define IDD_PROGRESS                    148
#define IDS_STURLA_GLYPH                149
#define IDB_INFOLIST                    149
#define IDS_RANNVEIG_GLYPH              150
#define IDB_IMAGELIST_INFO              150
#define IDS_JALGARD_GLYPH               151
#define IDD_TILEPERSO                   151
#define IDB_GAMECHATVIEW                151
#define IDS_CANT_COMPUTE_HIGH_QUALITY   152
#define IDD_TILEPERSOLIST               152
#define IDB_GAMEPLAYERVIEW              152
#define IDS_NB_PLAYER                   153
#define IDB_GAMEACTIONVIEW              153
#define IDS_MUST_ACTIVATE_SHADOW_FOR_HIGH_QUALITY 154
#define IDD_JOINGAME                    154
#define IDS_CASTLE                      155
#define IDS_CASTLE_BASE_CORNER          156
#define IDD_WAITINGPLAYERS              156
#define IDS_CASTLE_BASE_STRAIGHT        157
#define IDD_CREATEGAME                  157
#define IDS_CASTLE_BASE_END             158
#define IDD_OBJECTVIEW                  158
#define IDS_CASTLE_WALL_CORNER          159
#define IDD_GAMEACTIONVIEW              159
#define IDS_CASTLE_WALL_STRAIGHT        160
#define IDD_CHOOSE_ARMY                 160
#define IDS_CASTLE_WALL_END             161
#define IDB_SHIELD                      161
#define IDS_CASTLE_WALL_WALK            162
#define IDB_ATTACK                      162
#define IDS_CASTLE_BATTLEMENT           163
#define IDB_VALIDATE                    163
#define IDS_CASTLE_DOOR                 164
#define IDB_MOVEMENT                    164
#define IDD_GET_ZOOM_VALUE              164
#define IDS_CASTLE_LADDER               165
#define IDB_RANGE                       165
#define IDD_RENDER_VIDEO                165
#define IDS_CASTLE_FLAG                 166
#define IDD_CHOOSELEVEL                 166
#define IDS_LANGUAGE                    167
#define IDR_TOOLBARGAME                 167
#define IDS_INFOWINDOW                  168
#define IDB_GAMETOOLBAR                 168
#define IDS_INFOBAR                     169
#define IDD_GET_DICE_RESULT             169
#define IDB_LIFE                        169
#define IDS_INFO_COLUMN                 170
#define IDB_PREDICTEDPLAYSHOWX          170
#define IDD_JOINLISTGAME                170
#define IDS_WARNING                     171
#define IDB_PREDICTEDPLAYSHOW1          171
#define IDS_INFORMATION                 172
#define IDB_PREDICTEDPLAYSHOW2          172
#define IDS_CRITICAL                    173
#define IDB_PREDICTEDPLAYSHOW3          173
#define IDS_NOTHING_UNDER_TILE          174
#define IDB_PREDICTEDPLAYHIDEX          174
#define IDS_NBTILE_ANDZMAX              175
#define IDB_PREDICTEDPLAYHIDE1          175
#define IDS_OTHER_TILE_AT_SAME_PLACE    176
#define IDB_PREDICTEDPLAYHIDE2          176
#define ID_INDICATOR_CURRENT_TILE       177
#define IDB_PREDICTEDPLAYHIDE3          177
#define IDS_NBMASTERSET_ETC             178
#define IDB_PREDICTEDPLAYHIDE           178
#define IDS_CANT_LOW_LEVEL              179
#define IDB_PREDICTEDPLAYMASK           179
#define IDS_NORMAL                      180
#define IDS_SRMALLOY                    181
#define IDS_PERSONAL_HEX                182
#define IDS_TILEPERSO_LIST              183
#define IDS_NONAME                      184
#define IDS_FIGURE                      185
#define IDS_NEGOKSA                     186
#define IDS_AGENTCARR                   187
#define IDS_MIMRING                     188
#define IDS_SYVARRIS                    189
#define IDS_MARCHEMORT9000              190
#define IDS_SGTDRAKEALEXANDER           191
#define IDS_GRIMNAK                     192
#define IDS_FINNLECHAMPIONVIKING        193
#define IDS_RAELINLAGUERRIEREKYRIE      194
#define IDS_THORGRIMLECHAMPIONVIKING    195
#define IDS_GUERRIERSMARRO1_4           196
#define IDS_GUERRIERSMARRO2_4           197
#define IDS_GUERRIERSMARRO3_4           198
#define IDS_GUERRIERSMARRO4_4           199
#define IDR_VIRTUALSCAPE3D              200
#define IDS_GUARDSZETTIAN1_2            201
#define IDS_GUARDSZETTIAN2_2            202
#define IDS_GUERRIERSVIKINGTARN1_4      203
#define IDS_GUERRIERSVIKINGTARN2_4      204
#define IDS_GUERRIERSVIKINGTARN3_4      205
#define IDS_GUERRIERSVIKINGTARN4_4      206
#define IDS_ELITEAEROPORTEE1_4          207
#define IDS_ELITEAEROPORTEE2_4          208
#define IDS_ELITEAEROPORTEE3_4          209
#define IDS_ELITEAEROPORTEE4_4          210
#define IDS_SAMURAI_IZUMI1_3            211
#define IDS_SAMURAI_IZUMI2_3            212
#define IDS_SAMURAI_IZUMI3_3            213
#define IDS_AGENTS_KRAV_MAGA1_3         214
#define IDS_AGENTS_KRAV_MAGA2_3         215
#define IDS_AGENTS_KRAV_MAGA3_3         216
#define IDS_CASTLE_ARCH                 217
#define IDS_NOTHING_SELECTED            218
#define IDS_DISPLAY_SELECTED            219
#define IDS_DEFAULTGAMENAME             220
#define IDS_DEFAULTGAMEWELCOMEMESSAGE   221
#define IDS_FILL_PLAYER_NAME            222
#define IDS_FILL_GAME_NAME              223
#define IDS_FILL_GAME_POINT             224
#define IDS_PLAYER_MAX_TOO_LOW          225
#define IDS_COLUMN_HEADER_PLAYER        226
#define IDS_COLUMN_HEADER_WATCHER       227
#define IDR_VIRTUALSCAPEGAME3D          228
#define IDS_PT_CLIENT                   229
#define IDS_PT_SERVER                   230
#define IDS_BAD_SERVER_VERSION_FOR_GAME 231
#define IDS_GAMECHATWINDOW              232
#define IDS_GAMEPLAYERWINDOW            233
#define IDS_GAMEPLAYERVIEW              234
#define IDS_GAMECHATVIEW                235
#define IDS_GAMEACTIONVIEW              236
#define IDS_GAMEACTIONWINDOW            237
#define IDS_ACTION_CHOOSE_ARMY          238
#define IDS_ACTION_UNKNOWN              239
#define IDS_POINTFORARMY                240
#define IDS_AGENTCARRNAME               241
#define IDS_AGENTCARRBASICRULE          242
#define IDS_AGENTCARREXPERTRULE         243
#define IDS_SAMOURAISIZUMINAME          244
#define IDS_SAMOURAISIZUMIBASICRULE     245
#define IDS_SAMOURAISIZUMIEXPERTRULE    246
#define IDS_ACTION_PLACE_ARMY           247
#define IDS_AGENTSDEKRAVMAGANAME        248
#define IDS_ELITEAEROPORTEENAME         249
#define IDS_FINNLECHAMPIONVIKINGNAME    250
#define IDS_GARDESZETTIENSNAME          251
#define IDS_GRIMNAKNAME                 252
#define IDS_GUERRIERSMARRONAME          253
#define IDS_GUERRIERSVIKINGSDETARNNAME  254
#define IDS_MARCHEMORT9000NAME          255
#define IDS_MIMRINGNAME                 256
#define IDS_NEGOKSANAME                 257
#define IDS_RAELINLAGUERRIEREKYRIENAME  258
#define IDS_SGTDRAKEALEXANDERNAME       259
#define IDS_SYVARRISNAME                260
#define IDS_THORGRIMLECHAMPIONVIKINGNAME 261
#define IDS_MARVEL                      262
#define IDS_SWAMPWATER                  263
#define IDS_SWAMP                       264
#define IDS_CONCRETE                    265
#define IDS_ASPHALT                     266
#define IDS_SWARM                       267
#define IDS_RUINBREAKED                 268
#define IDS_SIZE                        269
#define IDS_BASIC                       270
#define IDS_TUNDRA                      271
#define IDS_FORTRESS                    272
#define IDS_VOLCARREN                   273
#define IDS_TICALLA                     274
#define IDC_TAB_OBJECT_TYPE             1000
#define IDC_ED_MAT_GRASS24              1005
#define IDC_ED_MAT_GRASS7               1006
#define IDC_SP_MAT_GRASS24              1007
#define IDC_SP_MAT_GRASS7               1008
#define IDC_ED_MAT_GRASS3               1009
#define IDC_SP_MAT_GRASS3               1010
#define IDC_ED_MAT_GRASS2               1011
#define IDC_SP_MAT_GRASS2               1012
#define IDC_ED_MAT_GRASS1               1013
#define IDC_SP_MAT_GRASS1               1014
#define IDC_ED_MAT_ROCK24               1015
#define IDC_SP_MAT_ROCK24               1016
#define IDC_ED_MAT_ROCK7                1017
#define IDC_SP_MAT_ROCK7                1018
#define IDC_ED_MAT_ROCK3                1019
#define IDC_SP_MAT_ROCK3                1020
#define IDC_ED_MAT_ROCK2                1021
#define IDC_SP_MAT_ROCK2                1022
#define IDC_ED_MAT_ROCK1                1023
#define IDC_SP_MAT_ROCK1                1024
#define IDC_ED_MAT_SAND7                1025
#define IDC_SP_MAT_SAND7                1026
#define IDC_ED_MAT_SAND3                1027
#define IDC_SP_MAT_SAND3                1028
#define IDC_ED_MAT_SAND2                1029
#define IDC_SP_MAT_SAND2                1030
#define IDC_ED_MAT_SAND1                1031
#define IDC_SP_MAT_SAND1                1032
#define IDC_ED_MAT_LAVAFIELD7           1033
#define IDC_SP_MAT_LAVAFIELD7           1034
#define IDC_ED_MAT_LAVAFIELD2           1035
#define IDC_SP_MAT_LAVAFIELD2           1036
#define IDC_ED_MAT_LAVAFIELD1           1037
#define IDC_SP_MAT_LAVAFIELD1           1038
#define IDC_ED_MAT_ROAD5                1039
#define IDC_SP_MAT_ROAD5                1040
#define IDC_ED_MAT_ROAD2                1041
#define IDC_SP_MAT_ROAD2                1042
#define IDC_ED_MAT_ROAD1                1043
#define IDC_SP_MAT_ROAD1                1044
#define IDC_ED_MAT_WATER1               1045
#define IDC_SP_MAT_WATER1               1046
#define IDC_ED_MAT_LAVA1                1047
#define IDC_SP_MAT_LAVA1                1048
#define IDC_ED_MAT_ICE1                 1049
#define IDC_SP_MAT_ICE1                 1050
#define IDC_ED_MAT_SNOW2                1051
#define IDC_SP_MAT_SNOW2                1052
#define IDC_ED_MAT_SNOW1                1053
#define IDC_SP_MAT_SNOW1                1054
#define IDC_ED_MAT_RUIN3                1055
#define IDC_SP_MAT_RUIN3                1056
#define IDC_ED_MAT_RUIN2                1057
#define IDC_SP_MAT_RUIN2                1058
#define IDC_ED_MAT_TREE15               1059
#define IDC_SP_MAT_TREE15               1060
#define IDC_ED_MAT_TREE12               1061
#define IDC_SP_MAT_TREE12               1062
#define IDC_ED_MAT_TREE11               1063
#define IDC_SP_MAT_TREE11               1064
#define IDC_ED_MAT_TREE10               1065
#define IDC_SP_MAT_TREE10               1066
#define IDC_ED_MAT_GLACIER6             1067
#define IDC_SP_MAT_GLACIER6             1068
#define IDC_ED_MAT_GLACIER4             1069
#define IDC_SP_MAT_GLACIER4             1070
#define IDC_ED_MAT_GLACIER3             1071
#define IDC_SP_MAT_GLACIER3             1072
#define IDC_ED_MAT_GLACIER1             1073
#define IDC_SP_MAT_GLACIER1             1074
#define IDC_ED_MAT_WALL4                1075
#define IDC_SP_MAT_WALL4                1076
#define IDC_ED_MAT_GLYPHA               1077
#define IDC_SP_MAT_GLYPHA               1078
#define IDC_ED_MAT_GLYPHG               1079
#define IDC_SP_MAT_GLYPHG               1080
#define IDC_ED_MAT_GLYPHI               1081
#define IDC_SP_MAT_GLYPHI               1082
#define IDC_ED_MAT_GLYPHV               1083
#define IDC_SP_MAT_GLYPHV               1084
#define IDC_BT_ERASE_ALL                1085
#define IDC_BT_ADD_MASTER_SET           1086
#define IDC_EDIT_BATTLEFIELDNAME        1086
#define IDC_ED_MAT_GLYPHD               1087
#define IDC_EDIT_AUTHOR                 1087
#define IDC_SP_MAT_GLYPHD               1088
#define IDC_COMBO_LEVELBYPAGE           1088
#define IDC_BT_ADD_FORGOTTEN_FOREST     1089
#define IDC_EDIT_PRINTTRANSPARENCY      1089
#define IDC_BT_ADD_VOLCAREN_WASTELAND   1090
#define IDC_SP_PRINT_TRANSPARENCY       1090
#define IDC_ED_MAT_GLYPHB               1091
#define IDC_EDIT_PLAYER_NUMBER          1091
#define IDC_SP_MAT_GLYPHB               1092
#define IDC_ED_MAT_GLYPHK               1093
#define IDC_CHECK_PRINTGRID             1093
#define IDC_SP_MAT_GLYPHK               1094
#define IDC_SLIDER_SHADOW_QUALITY       1094
#define IDC_CHECK_PRINT_TILE_NUMBER     1094
#define IDC_ED_MAT_GLYPHE               1095
#define IDC_SLIDER_SHADOW_CONTRAST      1095
#define IDC_CHECK_PRINT_START_AREA_AS_LEVEL 1095
#define IDC_SP_MAT_GLYPHE               1096
#define IDC_SLIDER_PHOTO_QUALITY        1096
#define IDC_PROGRESS_BAR                1096
#define IDC_ED_MAT_GLYPHM               1097
#define IDC_SLIDER_PHOTO_DEPTH_FIELD_QUALITY 1097
#define IDC_SP_MAT_GLYPHM               1098
#define IDC_SLIDER_PHOTO_DEPTH_FIELD_QUALITY2 1098
#define IDC_SLIDER_PHOTO_LUMINOSITY     1098
#define IDC_BT_ADD_TUNDRA               1099
#define IDC_ED_MAT_GLYPHL               1100
#define IDC_SP_MAT_GLYPHL               1101
#define IDC_EDIT_SCENARIO               1101
#define IDC_ED_MAT_GLYPHS               1102
#define IDC_SP_MAT_GLYPHS               1103
#define IDC_CHECK_DEPTH_FIELD           1103
#define IDC_ED_MAT_GLYPHR               1104
#define IDC_ED_DEPTHFIELD_APERTURE      1104
#define IDC_SP_MAT_GLYPHR               1105
#define IDC_SP_DEPTHFIELD_APERTURE      1105
#define IDC_ED_MAT_GLYPHJ               1106
#define IDC_ED_DEPTHFIELD_DISTANCE      1106
#define IDC_SP_MAT_GLYPHJ               1107
#define IDC_SP_DEPTHFIELD_DISTANCE      1107
#define IDC_BT_ADD_TERRAIN              1108
#define IDC_CHECK_DISPLAY_TABLE         1108
#define IDC_ED_MAT_CASTLE_BCORNER       1109
#define IDC_BT_BACKGROUNDCOLOR3D        1109
#define IDC_SP_MAT_CASTLE_BCORNER       1110
#define IDC_BT_BACKGROUNDCOLOR2D        1110
#define IDC_ED_MAT_CASTLE_BSTRAIGHT     1111
#define IDC_COMBO_TEXTURE_TYPE          1111
#define IDC_SP_MAT_CASTLE_BSTRAIGHT     1112
#define IDC_EDIT_TILETYPENAME           1112
#define IDC_BT_TOPOGRAPHICCOLORHIGH     1112
#define IDC_ED_MAT_CASTLE_BEND          1113
#define IDC_COMBO_TILEPERSONBHEX        1113
#define IDC_BT_TOPOGRAPHICCOLORLOW      1113
#define IDC_SP_MAT_CASTLE_BEND          1114
#define IDC_EDIT_TILEPERSONBDISPO       1114
#define IDC_COMBO_ANAGLYPHIQUE_MODE     1114
#define IDC_ED_MAT_CASTLE_WCORNER       1115
#define IDC_SP_TILEPERSONBDISPO         1115
#define IDC_SP_MAT_CASTLE_WCORNER       1116
#define IDC_EDIT_TILEPERSOCAR           1116
#define IDC_ED_MAT_CASTLE_WSTRAIGHT     1117
#define IDC_COMBO_TILEPERSOTEXTURE      1117
#define IDC_SP_MAT_CASTLE_WSTRAIGHT     1118
#define IDC_COMBO_TILEPERSOTEXTURESIDE  1118
#define IDC_ED_MAT_CASTLE_WEND          1119
#define IDC_LIST_TILEPERSO              1119
#define IDC_SP_MAT_CASTLE_WEND          1120
#define IDC_BUTTON_ADDTILEPERSO         1120
#define IDC_ED_MAT_CASTLE_9             1121
#define IDC_BUTTON2                     1121
#define IDC_BT_COLOR2D                  1121
#define IDC_BUTTON_REMOVE               1121
#define IDC_SP_MAT_CASTLE_9             1122
#define IDC_BUTTON3                     1122
#define IDC_BUTTON_MODIFY               1122
#define IDC_COMBO_UNIT                  1122
#define IDC_ED_MAT_CASTLE_7             1123
#define IDC_SP_MAT_CASTLE_7             1124
#define IDC_ED_MAT_CASTLE_1             1125
#define IDC_SP_MAT_CASTLE_1             1126
#define IDC_ED_MAT_CASTLE_BATTLEMENT    1127
#define IDC_SP_MAT_CASTLE_BATTLEMENT    1128
#define IDC_ED_MAT_CASTLE_DOOR          1129
#define IDC_SP_MAT_CASTLE_DOOR          1130
#define IDC_BT_ADD_CASTLE               1131
#define IDC_ED_MAT_CASTLE_LADDER        1132
#define IDC_SP_MAT_CASTLE_LADDER        1133
#define IDC_ED_MAT_CASTLE_FLAG          1134
#define IDC_SP_MAT_CASTLE_FLAG          1135
#define IDC_BT_SAVE_COLLECTION          1136
#define IDC_BT_LOAD_COLLECTION2         1137
#define IDC_EDIT_GAME_NAME              1137
#define IDC_EDIT_GAME_PASSWORD          1138
#define IDC_ED_MAT_MARVEL_CONCRETE7     1138
#define IDC_EDIT_PLAYERS_MAX            1139
#define IDC_SP_MAT_MARVEL_CONCRETE7     1139
#define IDC_SPIN_PLAYERS_MAX            1140
#define IDC_ED_MAT_MARVEL_CONCRETE2     1140
#define IDC_EDIT_WATCHER_MAX            1141
#define IDC_SP_MAT_MARVEL_CONCRETE2     1141
#define IDC_SPIN_WATCHER_MAX            1142
#define IDC_ED_MAT_MARVEL_CONCRETE1     1142
#define IDC_COMBO_GAME_TYPE             1143
#define IDC_SP_MAT_MARVEL_CONCRETE1     1143
#define IDC_EDIT_GAME_POINT             1144
#define IDC_ED_MAT_MARVEL_ASPHALT7      1144
#define IDC_SPIN_GAME_POINT             1145
#define IDC_SP_MAT_MARVEL_ASPHALT7      1145
#define IDC_EDIT_WELCOME_MESSAGE        1146
#define IDC_ED_MAT_MARVEL_ASPHALT2      1146
#define IDC_EDIT_SERVER_PORT            1147
#define IDC_SP_MAT_MARVEL_ASPHALT2      1147
#define IDC_SPIN_SERVER_PORT            1148
#define IDC_ED_MAT_MARVEL_ASPHALT1      1148
#define IDC_CHECK_GAME_WAVE1            1149
#define IDC_SP_MAT_MARVEL_ASPHALT1      1149
#define IDC_CHECKGAME_WAVE2             1150
#define IDC_LIST_PLAYERS_CONNECTED      1150
#define IDC_ED_MAT_MARVEL_RUIN6         1150
#define IDC_CHECK_GAME_WAVE3            1151
#define IDC_LIST_WATCHER_CONNECTED      1151
#define IDC_SP_MAT_MARVEL_RUIN6         1151
#define IDC_CHECK_GAME_WAVE4            1152
#define IDC_ED_MAT_SWAMP24              1152
#define IDC_CHECK_GAME_WAVE5            1153
#define IDC_EDIT_MESSAGE                1153
#define IDC_SP_MAT_SWAMP24              1153
#define IDC_CHECK_GAME_WAVE6            1154
#define IDC_BUTTON_SEND_MESSAGE         1154
#define IDC_ED_MAT_SWAMP7               1154
#define IDC_EDIT_PLAYER_NAME            1155
#define IDC_SP_MAT_SWAMP7               1155
#define IDC_RICHEDIT_SCENARIO           1156
#define IDC_CHECK_GAME_WAVE2            1156
#define IDC_CHECK_GAME_EXTENSION        1156
#define IDC_ED_MAT_SWAMP3               1156
#define IDC_EDIT_IP                     1156
#define IDC_BUTTON_BOLD                 1157
#define IDC_SP_MAT_SWAMP3               1157
#define IDC_CHECK_GAME_WAVE7            1157
#define IDC_BUTTON_UNDERLINE            1158
#define IDC_ED_MAT_SWAMP2               1158
#define IDC_CHECK_GAME_WAVE8            1158
#define IDC_BUTTON_ITALIC               1159
#define IDC_SP_MAT_SWAMP2               1159
#define IDC_CHECK_GAME_WAVE9            1159
#define IDC_BUTTON_TEXTCOLOR            1160
#define IDC_ED_MAT_SWAMP1               1160
#define IDC_EDIT_GAME_LANGAGE           1160
#define IDC_BUTTON_BACKCOLOR            1161
#define IDC_SERVER_IP_ADDRESS           1161
#define IDC_SP_MAT_SWAMP1               1161
#define IDC_ED_MAT_SWAMP_WATER1         1162
#define IDC_SP_MAT_SWAMP_WATER1         1163
#define IDC_BATTLEFIELD_NAME            1164
#define IDC_BT_ADD_MARVEL               1164
#define IDC_PLAYER_MAX                  1165
#define IDC_BT_ADD_SWARM                1165
#define IDC_GAME_POINT                  1166
#define IDC_RICHEDIT_MESSAGE            1166
#define IDC_ED_MAT_GLYPHW               1166
#define IDC_SP_MAT_GLYPHW               1167
#define IDC_BUTTON_SEND                 1168
#define IDC_ED_MAT_GLYPHP               1168
#define IDC_RICHEDIT_CHAT               1169
#define IDC_SP_MAT_GLYPHP               1169
#define IDC_RICHEDIT_ACTION             1170
#define IDC_ED_MAT_GLYPHO               1170
#define IDC_POINTFORARMY                1171
#define IDC_SP_MAT_GLYPHO               1171
#define IDC_EDIT_ZOOM_VALUE             1172
#define IDC_ED_MAT_GLYPHN               1172
#define IDC_SP_MAT_GLYPHN               1173
#define IDC_ED_MAT_GLYPHC               1174
#define IDC_RENDER_IMAGENUMBER          1174
#define IDC_SP_MAT_GLYPHC               1175
#define IDC_RENDER_HIGHQUALITY          1175
#define IDC_ED_MAT_GLYPHT               1176
#define IDC_RENDER_FIRSTIMAGE           1176
#define IDC_SP_MAT_GLYPHT               1177
#define IDC_RENDER_LASTIMAGE            1177
#define IDC_ED_MAT_GLYPHU               1178
#define IDC_RENDER_FILE                 1178
#define IDC_SP_MAT_GLYPHU               1179
#define IDC_BUTTON_RENDER_FILE          1179
#define IDC_ED_MAT_SWAMP_HIVE6          1180
#define IDC_RENDER_SPIN_LASTIMAGE       1180
#define IDC_SP_MAT_SWAMP_HIVE6          1181
#define IDC_RENDER_SPIN_FIRSTIMAGE      1181
#define IDC_CHECK_MOVE_SOLIDSCAPE       1181
#define IDC_RENDER_SPINNUMBERIMAGE      1182
#define IDC_ED_LEVEL                    1182
#define IDC_ED_MAT_TICALLAPALM          1182
#define IDC_SP_LEVEL                    1183
#define IDC_SP_MAT_TICALLAPALM          1183
#define IDC_ED_MAT_TICALLAGRASS         1184
#define IDC_SP_MAT_TICALLAGRASS         1185
#define IDC_ED_DICE_NUMBER_TO_LAUNCH    1185
#define IDC_BT_ADD_VOLCAREN_WASTELAND2  1186
#define IDC_BT_ADD_TICALLA_JUNGLE       1186
#define IDC_SP_DICE_NUMBER_TO_LAUNCH    1186
#define IDC_ED_MAT_DUNGEON24            1187
#define IDC_CHECK_FORCE_RESULT          1187
#define IDC_SP_MAT_DUNGEON24            1188
#define IDC_ED_DICE_NUMBER_RESULT       1188
#define IDC_ED_MAT_DUNGEON7             1189
#define IDC_SP_DICE_NUMBER_RESULT       1189
#define IDC_SP_MAT_DUNGEON7             1190
#define IDC_BT_LAUNCH_DICE              1190
#define IDC_ED_MAT_DUNGEON3             1191
#define IDC_SP_MAT_DUNGEON3             1192
#define IDC_BUTTON1                     1192
#define IDC_ED_MAT_DUNGEON2             1193
#define IDC_GAMELIST                    1193
#define IDC_SP_MAT_DUNGEON2             1194
#define IDC_ED_MAT_DUNGEON1             1195
#define IDC_SP_MAT_DUNGEON1             1196
#define IDC_ED_MAT_DUNGEON_SHADOW1      1197
#define IDC_SP_MAT_DUNGEON_SHADOW1      1198
#define IDC_ED_MAT_DUNGEON_OUTCROP1     1199
#define IDC_SP_MAT_DUNGEON_OUTCROP1     1200
#define IDC_ED_MAT_DUNGEON_OUTCROP3     1201
#define IDC_SP_MAT_DUNGEON_OUTCROP3     1202
#define IDC_BT_ADD_DUNGEON              1203
#define ID_FILE_MYPRINT                 26457
#define ID_ZOOMIN                       32772
#define ID_OUTILS_ZOOMPOSITIF           32775
#define ID_OUTILS_ZOOMN32776            32776
#define ID_ZOOMOUT                      32777
#define ID_OUTILS_VOIRTOUT              32778
#define ID_FULLVIEW                     32779
#define ID_LEVELUP                      32780
#define ID_LEVELDOWN                    32781
#define ID_OUTILS_NIVEAUSUP32782        32782
#define ID_OUTILS_NIVEAUINF32783        32783
#define ID_EDIT_ROTATE_RIGHT            32786
#define ID_EDIT_REMOVE                  32788
#define ID_S32789                       32789
#define ID_S32790                       32790
#define ID_dfd                          32791
#define ID_EDIT_ROTATE_LEFT             32792
#define ID_FEN32795                     32795
#define ID_NEW_3DVIEW                   32796
#define ID_CONFIGURATION_MAT32797       32797
#define ID_CONFIGURATION_MAT_DISPO      32798
#define ID_CONFIGURATION_PARAM32799     32799
#define ID_CONFIGURATION_PARAMDOC       32800
#define ID_AFFICHAGE_BARRED             32801
#define ID_AFFICHAGE_BARRED32802        32802
#define ID_AFFICHAGE_BARRE2D            32803
#define ID_AFFICHAGE_BARREOBJET         32804
#define IDR_TOOLBAR3DVIEW               32805
#define IDR_TOOLBAR3D_DISPLAYSHADOW     32805
#define ID_AFFICHAGE_BARRED32806        32806
#define ID_AFFICHAGE_BARRED3D           32807
#define ID_S32808                       32808
#define ID_S32809                       32809
#define ID_S32810                       32810
#define ID_SELECT_NOTHING               32811
#define ID_SELECT_ALL                   32812
#define ID_SELECT_INVERSE               32813
#define ID_S32814                       32814
#define ID_SELECT_LEVELUP               32815
#define ID_S32816                       32816
#define ID_SELECT_LEVELDOWN             32817
#define ID_OUTILS_INVERS32818           32818
#define ID_OUTILS_REVERSE               32819
#define ID_CONFIGURATION_PR32820        32820
#define ID_CONFIGURATION_PREFERENCY     32821
#define ID_OUTILS_VUEHAUTEQUALIT32822   32822
#define ID_OUTILS_VUEHAUTEQUALITE       32823
#define ID_CAMERA_GO_HOME               32825
#define ID_OUTILS_VUED                  32826
#define ID_OUTILS_TOURNEAUTOUR          32827
#define ID_OUTILS_VOIRLACONSTRUCTION    32830
#define ID_S32837                       32837
#define ID_SELECT_LEVEL                 32838
#define ID_AFFICHAGE_FEN32844           32844
#define ID_AFFICHAGE_FENETRE_OBJET      32845
#define ID_AFFICHAGE_FENETREINFORMATION 32846
#define ID_DOC_CHECK                    32848
#define ID_OUTILS_SAUVERL               32857
#define ID_OUTILS_SAVEIMAGE             32858
#define ID_AIDE_AIDEGLOBALE             32859
#define ID_CONFIGURATION_PI32862        32862
#define ID_CONFIGURATION_TILEPERSO      32863
#define ID_EDITION_COUPER               32864
#define ID_EDITION_COLLER               32865
#define ID_EDITION_COPIER               32866
#define ID_JOUER_C32867                 32867
#define ID_JOUER_REJOINDREUNEPARTIEENLIGNEOUR32868 32868
#define ID_JOUER_VOIRUNEPARTIEENLIGNEOUR32869 32869
#define ID_PLAY_CREATEGAME              32870
#define ID_PLAY_JOINGAME                32871
#define ID_PLAY_WATCHGAME               32872
#define ID_AFFICHAGE_FEN32873           32873
#define ID_AFFICHAGE_CHAT               32874
#define ID_AFFICHAGE_FEN32875           32875
#define ID_AFFICHAGE_WINDOWPLAYER       32876
#define ID_AFFICHAGE_FEN32877           32877
#define ID_AFFICHAGE_WINDOW_ACTION      32878
#define ID_JOUER_QUITTERLEJEU           32879
#define ID_ZOOMVALUE                    32880
#define ID_OUTILS_NUM32881              32881
#define ID_OUTILS_NUMBER                32882
#define ID_FICHIER_IMPRIMERNUM32883     32883
#define ID_FICHIER_APER32884            32884
#define ID_FICHIER_IMPRIMERNUM          32885
#define ID_FICHIER_APERCUNUM            32886
#define ID_VID32887                     32887
#define ID_VID32888                     32888
#define ID_VID32889                     32889
#define ID_VID32890                     32890
#define ID_VIDEO_ERASE_ALL_POSITION     32891
#define ID_VIDEO_ADD_CURRENT_POSITION   32892
#define ID_VIDEO_MOVE_REALTIME          32893
#define ID_VIDEO_CREATE_FILE            32894
#define ID_OUTILS_INS32895              32895
#define ID_OUTILS_SUPPRIMERLENIVEAUACTUEL 32896
#define ID_OUTILS_INSERTLEVEL           32897
#define ID_OUTILS_REMOVELEVEL           32898
#define ID_BUTTON32899                  32899
#define ID_VID32903                     32903
#define ID_VID32904                     32904
#define ID_VIDEO_SAVE_POSITION          32905
#define ID_VIDEO_LOAD_POSITION          32906
#define ID_OUTILS_ALLER32907            32907
#define ID_OUTILS_GO_LEVEL              32908
#define ID_OUTILS_VUETOPOGRAPHIQUE      32912
#define ID_OUTILS_VUEST32914            32914
#define ID_OUTILS_VUESTEREO             32915
#define ID_OUTILS_VUESTEREOINTERLACED   32916
#define ID_S32917                       32917
#define ID_SELECT_SAME_TILE_SAME_LEVEL  32918
#define ID_PLACE_FIGURE_ON_MAP          32919
#define ID_REMOVE_FIGURE_FROM_MAP       32920
#define ID_JOUER_SUPPRIMEUNEFIGURINEDELACARTE 32921
#define ID_MOVE_FIGURE                  32922
#define ID_JOUER_D32923                 32923
#define ID_ATTACK_CHOOSE_FIGURE         32924
#define ID_ATTACK_DICE                  32925
#define ID_DEFENSE_DICE                 32926
#define ID_NEXT_TURN                    32927
#define ID_OUTILS_SAUVERLEREPLAYDELAPARTIE 32930
#define ID_OUTILS_ANIMATIONSTOURNANTE   32931
#define ID_OUTILS_ANIMATIONSSIMPLES     32932
#define ID_OUTILS_PASD                  32933
#define ID_OUTILS_NOANIMATION           32934
#define ID_OUTILS_ANIMATIONSTOURNANTES  32935
#define ID_REPLAY_GAME                  32943
#define ID_REPLAY_TO_FILE               32944
#define ID_OUTILS_REPLAYDELAPARTIE      32945
#define ID_DIE_20                       32946

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32947
#define _APS_NEXT_CONTROL_VALUE         1194
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
